
// This file has been generated by the GUI designer. Do not modify.
namespace GtkDesafio3
{
	public partial class MainProgram
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget GtkDesafio3.MainProgram
			this.Name = "GtkDesafio3.MainProgram";
			this.Title = global::Mono.Unix.Catalog.GetString("MainProgram");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
