
// This file has been generated by the GUI designer. Do not modify.
namespace GtkDesafio3
{
	public partial class MainProgram
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action saveAction;

		private global::Gtk.Action printAction;

		private global::Gtk.Action dialogInfoAction;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Toolbar toolbar4;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Label label12;

		private global::Gtk.HBox hbox8;

		private global::Gtk.VBox vbox10;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Label label9;

		private global::Gtk.Entry entry6;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Label label10;

		private global::Gtk.Entry entry7;

		private global::Gtk.HBox hbox11;

		private global::Gtk.Label label11;

		private global::Gtk.Entry entry8;

		private global::Gtk.VBox vbox9;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Button button3;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeview4;

		private global::Gtk.Label GtkLabel2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget GtkDesafio3.MainProgram
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.saveAction = new global::Gtk.Action("saveAction", null, null, "gtk-save");
			w1.Add(this.saveAction, null);
			this.printAction = new global::Gtk.Action("printAction", null, null, "gtk-print");
			w1.Add(this.printAction, null);
			this.dialogInfoAction = new global::Gtk.Action("dialogInfoAction", null, null, "gtk-dialog-info");
			w1.Add(this.dialogInfoAction, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "GtkDesafio3.MainProgram";
			this.Title = global::Mono.Unix.Catalog.GetString("MainProgram");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child GtkDesafio3.MainProgram.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString("<ui><toolbar name=\'toolbar4\'><toolitem name=\'saveAction\' action=\'saveAction\'/><to" +
					"olitem name=\'printAction\' action=\'printAction\'/><toolitem name=\'dialogInfoAction" +
					"\' action=\'dialogInfoAction\'/></toolbar></ui>");
			this.toolbar4 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar4")));
			this.toolbar4.Name = "toolbar4";
			this.toolbar4.ShowArrow = false;
			this.vbox6.Add(this.toolbar4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.toolbar4]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("label12");
			this.label12.Justify = ((global::Gtk.Justification)(2));
			this.hbox12.Add(this.label12);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.label12]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox6.Add(this.hbox12);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox12]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			this.vbox10.BorderWidth = ((uint)(9));
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("label9");
			this.hbox9.Add(this.label9);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label9]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.entry6 = new global::Gtk.Entry();
			this.entry6.CanFocus = true;
			this.entry6.Name = "entry6";
			this.entry6.IsEditable = true;
			this.entry6.InvisibleChar = '•';
			this.hbox9.Add(this.entry6);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.entry6]));
			w6.Position = 1;
			this.vbox10.Add(this.hbox9);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox9]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("label10");
			this.hbox10.Add(this.label10);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label10]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.entry7 = new global::Gtk.Entry();
			this.entry7.CanFocus = true;
			this.entry7.Name = "entry7";
			this.entry7.IsEditable = true;
			this.entry7.InvisibleChar = '•';
			this.hbox10.Add(this.entry7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.entry7]));
			w9.Position = 1;
			this.vbox10.Add(this.hbox10);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox10]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("label11");
			this.hbox11.Add(this.label11);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.label11]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.entry8 = new global::Gtk.Entry();
			this.entry8.CanFocus = true;
			this.entry8.Name = "entry8";
			this.entry8.IsEditable = true;
			this.entry8.InvisibleChar = '•';
			this.hbox11.Add(this.entry8);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.entry8]));
			w12.Position = 1;
			this.vbox10.Add(this.hbox11);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox11]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.hbox8.Add(this.vbox10);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.vbox10]));
			w14.Position = 1;
			w14.Padding = ((uint)(84));
			this.vbox6.Add(this.hbox8);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox8]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString("Operar y guardar");
			this.hbox7.Add(this.button3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.button3]));
			w16.PackType = ((global::Gtk.PackType)(1));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			w16.Padding = ((uint)(16));
			this.vbox9.Add(this.hbox7);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox7]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(2));
			this.frame1.BorderWidth = ((uint)(2));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeview4 = new global::Gtk.TreeView();
			this.treeview4.CanFocus = true;
			this.treeview4.Name = "treeview4";
			this.GtkScrolledWindow.Add(this.treeview4);
			this.GtkAlignment.Add(this.GtkScrolledWindow);
			this.frame1.Add(this.GtkAlignment);
			this.GtkLabel2 = new global::Gtk.Label();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>GtkFrame</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel2;
			this.vbox9.Add(this.frame1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.frame1]));
			w21.Position = 1;
			this.vbox6.Add(this.vbox9);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vbox9]));
			w22.Position = 3;
			this.Add(this.vbox6);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 602;
			this.DefaultHeight = 448;
			this.Show();
		}
	}
}
